1907-Fusion/ocean-fusion

README.md

feat(readme): saved file

---

.travis.yml
CHANGELOG.md
client/components/auth-form.js
client/components/navbar.js
package-lock.json
package.json
public/index.html
script/deploy

feat(package.json): fixed error

---

client/components/auth-form.js
package-lock.json
package.json
public/index.html

feat(package.json): changing the boostrap to bootstrap

---

client/components/auth-form.js
public/style.css

feat(auth-form.js): finish touching up login and register form

---

client/components/navbar.js
public/style.css

feat(navbar): changed class name so colors don't appear in login form

---

script/seed.js
server/db/models/index.js
server/db/models/question.js

feat(seed): finished seeding our database with questions

---

script/seed.js

corrected the questions data

---

client/components/index.js
client/components/main.js
client/routes.js
public/style.css

feat(mainPage): spinning earth, how to play, and button added

---

client/components/navbar.js
server/api/index.js
server/api/questions.js
server/api/questions.spec.js

However, now that I think about it, the GET all questions route is not secure (e.g. anyone can view). I can either add security or we can get rid of the route...

Question api routes

---

client/components/game.js

feat(game.js): getting camera and posenet

---

client/components/game.js
public/style.css

styled the location of camera screen

---

client/components/camera.js
client/components/game.js
client/components/index.js
client/components/loading.js
public/style.css

loading is working

---

client/components/game.js
client/components/question.js
public/style.css

Question now displays beside camera. No styling yet.

feat(question-display): question and choices appear, no styling yet

---

client/components/camera.js
client/components/game.js
client/components/index.js
client/components/loading.js
public/style.css

feat(loading.js): css styling

---

public/style.css

Added some basic styling to questions.

feat(question-display): added some style to question choices

---

server/db/models/question.spec.js

teste are prepared for question models.

question model tests are ready

---

client/components/camera.js
public/style.css

feat(camera.js): loading width and height

---

client/components/camera.js
server/api/questions.js
server/api/users.js
server/db/models/user.js

api/users and api/questions is now protected from non-admin users.

the questions and users information is hidden from the nonadmin users

---

client/components/camera.js
public/style.css
server/api/questions.js

feat(camera.js): fix detectPose function placement

---

script/seed.js
server/db/models/question.js

Hey all, I didn't mean to work tonight initially, but I added some more seed data for our questions!
In the spirit of being educational, I also added an optional 'explanation' attribute to our Question model, with explanations for some of the answers (in case we have time and want this to appear somewhere).
There was also a duplicate question that I removed.

feat(seed.js): added more seed data

---

client/components/auth-form.js
client/components/camera.js
client/components/main.js
client/components/navbar.js
client/routes.js
client/store/user.js
public/style.css

feat(login): enabled login and register

---

client/components/fish.js
client/components/game.js
client/components/ocean.js
public/style.css

feat(animation): added animation

---

client/components/camera.js
public/style.css

I added basic circles on top of the camera. Just doing a PR now to try to avoid merge conflicts.

feat(answer-squares): added basic div squares

---

client/components/camera.js
public/style.css

Answer choices are now glowing circles (like our sun), and only appear after loading! We can readjust style once we review design later today.

feat(answer-squares): answer choices only appear after loading

---

client/components/fish.js
public/style.css

feat(fish.js): populating the fishes

---

client/components/camera.js
public/index.html
public/style.css

feat(camera.js): created timer function and background color

---

client/components/camera.js
client/components/question.js

feat(score): choices placed to the correct field on the camera. the state can be uopdated with the current question

---

client/components/camera.js

feat(camera.js): fixed the bracket

---

client/components/camera.js
client/components/game.js
client/components/navbar.js
public/style.css

I commented out the waterfilter for now for performance.
Score is styled. Circle answers are more styled, and are responsive. Video aspect ratio has been changed, but video size is determined by window size at time of video setup.

feat(camera, design, circle squares): resized camera, 

---

client/components/game.js
client/components/question.js
public/style.css

feat(style.css): resize fishTank and question container

---

client/components/camera.js

worked on the feature of toastifier

feat(score):message pops up when the correct answer is detected.

---

package-lock.json
package.json
public/style.css

feat(css): fix some css stuff

---

client/components/camera.js
client/components/fish.js
client/store/user.js
script/seed.js

I am putting this PR in early, as we want to modify camera.js and I know there have been previous changes made. Thank you!

feat(score and fish): score and fish multiplies correctly

---

client/components/camera.js
client/components/fish.js

Guys! 
I redid the fish.js so that it has better response with the fish generating. 
(GP... wants some recognition......) 
please approve mine. thank you!!!

feat(fish.js): eliminate componeneDidUpdate for better response

---

client/components/camera.js

The Game Over screen appears when the user gets 3 wrong answers. The question does not change when the user gets a wrong answer, though.

feat(game-over): game over screen appears when user gets 3 wrong answers

---

client/components/main.js

feat(mainPage): changes to time and directions

---

client/components/camera.js

feat(question): game over renders after 9 wrong answers

---

client/components/camera.js
client/components/fish.js
server/db/models/question.js

feat(camera): fixed positioning of circles and score

---

client/components/navbar.js
client/routes.js
client/store/user.js

feat(logout): redirecting to login page

---

client/components/camera.js

Created a timer and winning user is redirected to the victory page

feat(victory):winning user is redirected to the victory page

---

client/components/camera.js
client/components/fish.js
client/components/navbar.js
client/store/index.js
client/store/score.js
client/store/user.js

Score is now its own reducer, removed from the user reducer. Fish and Navbar have been updated too.

feat(score): score is now its own reducer

---

client/components/camera.js

Removed console logs and clarified winning condition.

feat(gameover): removed console logs, changed winning condition

---

client/components/camera.js
client/components/gameOver.js
client/components/victory.js

Score resets after game is over.

feat(score-reset): score resets after victory and gameover

---

client/store/question.spec.js
client/store/score.spec.js
client/store/user.spec.js

Wrote tests for all reducers. We now have 12 tests.

feat(tests): wrote tests for reducers

---

README.md

feat(readMe): revised images and details

---

client/components/camera.js
public/style.css

toastify featue is applied. Style added to the notifications.

feat(toastify): styled the notifies

---

package-lock.json
package.json

updated package.json to include react-toastify as a dev dependency.

feat(toasts): edited package json to include toastify

---

client/components/camera.js
client/components/navbar.js
public/style.css
server/auth/google.js

feat(css): fixed the button height

---

client/components/camera.js

feat(change): toastify and state

---

client/components/camera.js

feat(notification): 30s and 10s

---

client/components/camera.js
public/style.css

removed some comments and unnecessary code (e.g. p5 import)

Cleaning up

---

package.json

feat(package.json): change the name database

---

client/components/camera.js

cleaned up some of the camera code so it's more readable.

feat(camera): modularized camera code

---

README.md

changed image sizes for readme.

feat(readme): edited image sizes in readme

---

README.md

feat(readme): edited readme

---

client/components/gameOver.js
client/components/user-home.js
client/components/victory.js
client/store/score.js
public/style.css
server/api/users.js

gameover component updates the score.

feat(user-home): score saves after game over or victory

---

client/components/camera.js

slowed down detectPose and sped up toastify.

feat(camera): slowed down detectPose, sped up toastify

---

client/components/main.js

feat(mainPage): changed directions

---

README.md

feat(readMe): updated readMe

---

client/components/game.js
client/components/gameOver.js
client/components/victory.js

score resets after new game button is clicked.

feat(score): score resets when new game is clicked

---

README.md

feat(readMe): fixed text to heroku link
